match_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("singles/", views.UserList.as_view(), name="singles_list"),
    path("singles_search/<int:user_type>/", views.SinglesSearchView.as_view(), name="singles_search"),
    path("singles_search/", views.SinglesSearchView.as_view(), name="singles_search_blank"),
    path("user/<uuid:user_id>/", views.UserDetail.as_view(), name="user_detail"),
    path("shadchan_list/<uuid:single_id>/", views.ShadchanList.as_view(), name="select_shadchan_list_for_single"),
    path("shadchan_list/", views.ShadchanList.as_view(), name="shadchan_list"),
    path(
        "shadchan/<uuid:user_id>/", views.ShadchanDetail.as_view(), name="shadchan_detail"
    ),  # as of now the shadchan detail page is a link to the regular user detail page
    path("shadchan/shadchan_edit/", views.ShadchanEdit.as_view(), name="shadchan_edit_detail_page"),
    path("make_suggestion_for/<uuid:single_id>/", views.MakeASuggestionView.as_view(), name="make_suggestion_for"),
    path("make_suggestion/", views.MakeASuggestionView.as_view(), name="make_suggestion_blank"),
    path(
        "suggestion_payment_complete/<uuid:suggestion_id>/",
        views.SuggestionPaymentComplete.as_view(),
        name="suggestion_payment_complete",
    ),
    path(
        "suggestion_payment_failed/<uuid:suggestion_id>/",
        views.SuggestionPaymentFailed.as_view(),
        name="suggestion_payment_failed",
    ),
    path(
        "suggestion_singles_search_list/<int:gender>/",
        views.SuggestionSinglesSearchView.as_view(),
        name="suggestion_singles_search_list",
    ),
    path("users_suggestions/", views.UserSuggestionsView.as_view(), name="users_suggestions"),
    path("suggestions/", views.SuggestionsView.as_view(), name="suggestions"),
    path("report_suggestion/", views.ReportSuggestionView.as_view(), name="report_suggestion"),
    path(
        "add_view_to_suggestion/<uuid:suggestion_id>/",
        views.AddViewToSuggestion.as_view(),
        name="add_view_to_suggestion",
    ),
    # path("mark_working_on_it/", views.MarkWorkingOnItView.as_view(), name="mark_working_on_it"),
    # path('select_shadchan_to_contact/<uuid:single_id>/', views.ContactShadchanView.as_view(), name='select_shadchan_to_contact'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView
from django.conf.urls.static import static
from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from . import views
from accounts_app.views import CustomSignUpView
from django.views.decorators.cache import cache_page

urlpatterns = [
    # DJANGO ADMIN
    path("372Crown/", admin.site.urls),  # original path was 'admin/' changed to '372Crown' for security reasons
    # WAGTAIL APPS
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    # PROJECT APPS
    path("", views.HomePage.as_view(), name="home"),
    path("accounts/signup/", CustomSignUpView.as_view(), name="account_signup"),
    path("accounts/", include("allauth.urls")),
    path("account/", include("accounts_app.urls")),
    path("payments/", include("payments_app.urls")),
    path("match/", include("match_app.urls")),
    path("chats/", include("chats_app.urls")),
    path("select2/", include("django_select2.urls")),
    path("get_in_touch/", TemplateView.as_view(template_name="base/get_in_touch.html"), name="get_in_touch"),
    path("faq/", TemplateView.as_view(template_name="base/faq.html"), name="faq"),
    path("about/", views.AboutPage.as_view(), name="about"),
    path("contact/", views.ContactPage.as_view(), name="contact"),
    path("privecy-policy/", views.PrivacyPolicyPage.as_view(), name="privacy_policy"),
    path("temperament_analysis/", include("temperament_analysis_app.urls")),
    # path("about/", cache_page(60 * 60 * 24)(views.AboutPage.as_view()), name="about"),
    path("", include(wagtail_urls)),
]

handler403 = views.custom_403_view
handler404 = views.custom_404_view
handler500 = views.custom_500_view
handler429 = views.custom_429_view
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    import socket

    # Attempt to get the hostname and IPs, with a fallback
    try:
        hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    except socket.gaierror:
        hostname, ips = "localhost", ["127.0.0.1"]

match_app/models.py
from django.db import models
from utils.abstract_models import TimeStampedModel
import uuid
from django.core.exceptions import ValidationError
from accounts_app.models import CustomUser, ShadchanProfile, Profile
from django_countries.fields import CountryField
from django.contrib.postgres.fields import ArrayField

# from django_countries.fields import CountryField
# Create a model to store all suggestions made by people,


class Suggestion(TimeStampedModel):
    COPPER = 1
    SILVER = 2
    GOLD = 3
    PLATINUM = 4
    PLATINUM_PLUS = 5
    RANKING_CHOICES = (
        (COPPER, "Copper"),
        (SILVER, "Silver"),
        (GOLD, "Gold"),
        (PLATINUM, "Platinum"),
        (PLATINUM_PLUS, "Platinum Plus"),
    )

    ACTIVE_EMAIL_SENT = 0
    NOT_ACTIVE_FLAGGED = 1
    STATUS_CHOICES = [
        (ACTIVE_EMAIL_SENT, "Active - Email Sent"),
        (NOT_ACTIVE_FLAGGED, "Not Active - Suggestion Flagged"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    made_by = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="suggestions_made",
        help_text="The user that made the suggestion",
    )
    for_boy = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="suggestions_received_for_boy",
        help_text="The user that the suggestion was made for",
    )
    for_girl = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="suggestions_received_for_girl",
        help_text="The user that the suggestion was made for",
    )
    message = models.TextField(
        null=True, blank=True, help_text="The message that the user wrote when making the suggestion"
    )
    email = models.EmailField(
        null=True, blank=True, help_text="The email of the user that made the suggestion, if the user was not logged in"
    )
    phone_number = models.CharField(
        max_length=30,
        null=True,
        blank=True,
        help_text="The phone of the user that made the suggestion, if the user was not logged in",
    )
    # if there is no related boy object or if there is no girl object
    boys_first_name = models.CharField(null=True, blank=True, max_length=50)
    boys_last_name = models.CharField(null=True, blank=True, max_length=50)
    boys_mothers_name = models.CharField(null=True, blank=True, max_length=50)
    boys_fathers_name = models.CharField(null=True, blank=True, max_length=50)
    boys_age = models.PositiveIntegerField(null=True, blank=True)
    boys_country = CountryField()
    boys_city = models.CharField(null=True, blank=True, max_length=50)
    # now for the girl
    girls_first_name = models.CharField(null=True, blank=True, max_length=50)
    girls_last_name = models.CharField(null=True, blank=True, max_length=50)
    girls_mothers_name = models.CharField(null=True, blank=True, max_length=50)
    girls_fathers_name = models.CharField(null=True, blank=True, max_length=50)
    girls_age = models.PositiveIntegerField(null=True, blank=True)
    girls_country = CountryField()
    girls_city = models.CharField(null=True, blank=True, max_length=50)
    girls_sect = ArrayField(
        models.CharField(max_length=50, choices=Profile.SECT_CHOICES),
        default=list,
        blank=True,
    )
    boys_sect = ArrayField(
        models.CharField(max_length=50, choices=Profile.SECT_CHOICES),
        default=list,
        blank=True,
    )
    amount = models.PositiveIntegerField(null=True, blank=True)
    ranking = models.PositiveIntegerField(
        choices=RANKING_CHOICES, default=COPPER, help_text="how we rank how good the suggestion is"
    )
    is_active = models.BooleanField(default=False)
    status = models.IntegerField(choices=STATUS_CHOICES, null=True, blank=True)
    paid = models.BooleanField(default=False)
    stripe_checkout_session_id = models.CharField(max_length=255, null=True, blank=True)
    stripe_invoice_id = models.CharField(max_length=255, null=True, blank=True)
    # create a foreign key to users so that a suggestion can belong to many users
    tagged_users = models.ManyToManyField(
        CustomUser,
        related_name="tagged_suggestions",
        blank=True,
        help_text="The Shadchonim that are tagged in the suggestion",
    )
    # https://stackoverflow.com/questions/66289175/best-way-to-monitor-number-of-views-on-a-blog-post-in-django
    views = models.ManyToManyField(CustomUser, related_name="suggestions_viewed", blank=True)
    strikes = models.PositiveIntegerField(default=0, help_text="how many times the suggestion has been reported")

    @property
    def num_views(self):
        return self.views.count()

    """
        # use this when counting the shadchanim that that vied the suggestion
        if request.user.is_shadchan:
            suggestion.views.add(request.user)
    """

    def clean(self):
        super().clean()
        if not self.for_boy and not self.boys_first_name:
            raise ValidationError("No boy was submitted with the suggestion")
        if not self.for_girl and not self.girls_first_name:
            raise ValidationError("No girl was submitted with the suggestion")

    def __str__(self):
        return f"suggestion: {self.id}"

    # now add a database constraint not allowing both for_boy and boys_first_name to be empty
    class Meta:
        # sort by created
        ordering = ["-created"]


class ReportSuggestion(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    suggestion = models.ForeignKey(
        Suggestion, on_delete=models.CASCADE, related_name="reports", help_text="The suggestion that is being reported"
    )
    reporter = models.ForeignKey(
        ShadchanProfile,
        on_delete=models.CASCADE,
        related_name="reported_suggestions",
        help_text="The user that is reporting the suggestion",
    )
    message = models.TextField(help_text="The message that the reporter wrote when reporting the suggestion")


# create model to store shadchanim that have marked the suggesiton as they are working on it
class ShadchanWorkingOnSuggestion(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    suggestion = models.ForeignKey(
        Suggestion,
        on_delete=models.CASCADE,
        related_name="shadchanim_working_on",
        help_text="The suggestion that the shadchan is working on",
    )
    shadchan = models.ForeignKey(
        ShadchanProfile,
        on_delete=models.CASCADE,
        related_name="suggestions_working_on",
        help_text="The shadchan that is working on the suggestion",
    )

match_app/forms/user_detail_forms.py
# create a form for ChatFriendRequest model in which is in the chats_app
from django import forms
from chats_app.models import ChatFriendRequest


class ChatFriendRequestForm(forms.ModelForm):
    class Meta:
        model = ChatFriendRequest
        fields = ['message']
        widgets = {
            'message': forms.Textarea(attrs={'rows': 2, 'cols': 40, 'maxlength': 512, 'placeholder': 'Optional message to user'}),
        }
        labels = {
            'message': 'Send along a optional message to the shadchan',
        }

templates/match_app/shadchan_list.html
{% extends 'base/base.html' %}

{% block title %}Shandchan List{% endblock title %}

{% block content %}
<style>
  .table-container {
    max-height: 1300px;
    @media screen and (min-width: 1024px) {
        max-height: 700px;
    }
    max-width: 100%;
    overflow: auto;
    border: 1px solid #e5e7eb;
    border-radius: 0.5rem;
  }
  
  .table-container table {
    width: max-content;
    min-width: 100%;
  }
  
  .table-container thead {
    position: sticky;
    top: 0;
    background-color: #f9fafb;
    z-index: 1;
  }

  .table-container th,
  .table-container td {
    white-space: nowrap;
  }

    .highlight {
        background-color: lightyellow;
    }

</style>
<section class="lg:mx-24 sm:mx-10 my-9 min-h-full flex-grow">
 {% include "match_app/includes/shadchen_page_header.html" %}
<div class="px-4 sm:px-6 lg:px-8">
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full pb-2 align-middle table-container">
        <table class="min-w-full border-separate border-spacing-0">
      <thead>
        <tr>
          <th scope="col" class="sticky z-0 top-0 border-b border-gray-300 bg-white bg-opacity-75 py-3.5 pl-3 pr-3 text-left text-sm font-semibold text-gray-900 backdrop-blur backdrop-filter">Name</th>
          <th scope="col" class="sticky z-0 top-0 border-b border-gray-300 bg-white bg-opacity-75 px-3 py-3.5 text-left text-sm font-semibold text-gray-900 backdrop-blur backdrop-filter">Location</th>
          <th scope="col" class="sticky z-0 top-0 border-b border-gray-300 bg-white bg-opacity-75 px-3 py-3.5 text-left text-sm font-semibold text-gray-900 backdrop-blur backdrop-filter">Language</th>
          <th scope="col" class="sticky top-0 z-10 border-b border-gray-300 bg-white bg-opacity-75 px-3 py-3.5 text-left text-sm font-semibold text-gray-900 backdrop-blur backdrop-filter">Sect</th>
          <th scope="col" class="sticky z-10 top-0 border-b border-gray-300 bg-white bg-opacity-75 py-3.5 pr-4 backdrop-blur backdrop-filter sm:pr-6 lg:pr-8">
            <span class="sr-only">Select</span>
          </th>
        </tr>
      </thead>
      <tbody id="shadchan_search_results">
        {% for shadchan in shadchans %}
        <tr>
          <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500 border-b border-gray-200">{{shadchan.first_name}}  {{shadchan.last_name}}</td>
          {% comment %} {{shadchan.shadchan_profile.city}}, TODO: add city when we add a place for the shadchan to add it in there profile page {% endcomment %}
          <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500 border-b border-gray-200">{{shadchan.shadchan_profile.get_country_display}} </td>
          {% comment %} <td class="whitespace-nowrap border-b border-gray-200 hidden px-3 py-4 text-sm text-gray-500 lg:table-cell">{{shadchan.profile.language}}</td> {% endcomment %}
            <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500 border-b border-gray-200">
              {% for language in shadchan.shadchan_profile.language %}
                {{ language }}{% if not forloop.last %}, {% endif %}
            {% empty %}
                No Language Found
            {% endfor %}
            </td>
            <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500 border-b border-gray-200">
              {% for sect in shadchan.shadchan_profile.sect %}
                {{ sect }}{% if not forloop.last %}, {% endif %}
              {% empty %}
                No sect Found
              {% endfor %}
            </td>
          {% comment %} TODO: WHEN ACTIVITY RATING IS WORKING UNCOMMENT {% endcomment %}
          {% comment %} <td class="whitespace-nowrap border-b border-gray-200 px-3 py-4 text-sm text-gray-500">
            <span class="inline-flex items-center rounded-md  px-2 py-1 text-xs font-medium ring-1 ring-inset 
              {% if shadchan.shadchan_profile.activity_rating == 0 %} text-gray-700 bg-gray-50 ring-gray-600/20
              {% elif shadchan.shadchan_profile.activity_rating == 1 %} text-blue-700 bg-blue-50 ring-blue-600/20
              {% elif shadchan.shadchan_profile.activity_rating == 2 %} text-green-700 bg-green-50 ring-green-600/20
              {% elif shadchan.shadchan_profile.activity_rating == 3 %} text-yellow-700 bg-yellow-50 ring-yellow-600/20
              {% endif %}">{{ shadchan.shadchan_profile.get_activity_rating_display }}</span>
          </td> {% endcomment %}
          {% comment %} {{shadchan.shadchanprofile.secssesfuly_matches}} {% endcomment %}
          <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500 border-b border-gray-200">
            {% comment %} if the shadchan clicks his own profile it should take him to his own profile edit page {% endcomment %}
            
            {% if shadchan.id == request.user.id %}
              <a href="{% url 'shadchan_edit_detail_page' %}" class="text-indigo-600 hover:text-indigo-900">Veiw Your Profile<span class="sr-only"></span></a>
            {% else %}
            <a href="{% url 'shadchan_detail' shadchan.id %}" class="text-indigo-600 hover:text-indigo-900">Select<span class="sr-only"></span></a>
            {% endif %}
          </td>
        </tr>
        {% empty %}
          <tr>
            <td class="whitespace-nowrap border-b border-gray-200 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 lg:pl-8">NO DATA</td>
            <td class="whitespace-nowrap border-b border-gray-200 hidden px-3 py-4 text-sm text-gray-500 sm:table-cell">NO DATA</td>
            <td class="whitespace-nowrap border-b border-gray-200 hidden px-3 py-4 text-sm text-gray-500 lg:table-cell">NO DATA</td>
            <td class="relative whitespace-nowrap border-b border-gray-200 py-4 pr-4 pl-3 text-right text-sm font-medium sm:pr-8 lg:pr-8">
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
</div>
</div>
{% include 'match_app/user_pagination.html' with page=shadchans %} 
</section>
{% endblock content %}

templates/match_app/user_detail.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block title %}Profile page{% endblock title %}

{% block content %}

   {% if is_shadchan %}
      {% include "match_app/includes/shadchan_user_detail.html" %}
   {% else %}
      {% include "match_app/includes/public_user_detail.html" %}
   {% endif %}

{% endblock content %}

templates/match_app/users_suggestions.html
{% extends 'base/duplicate_base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}Control Center{% endblock title %}

{% block content %}
<style>
  .profile_doc input[type="checkbox"] {
    display: none;
  }
  .profile_doc label[for="profile_document-clear_id"] {
    display: none;
  }
  .profile_doc a {
    display: block;
    margin-button: 5px;
    margin-left: 0.5rem;
    --tw-text-opacity: 1;
    color: rgb(75 85 99 / var(--tw-text-opacity));
    line-height: 1.5rem/* 24px */;
    font-size: 0.875rem/* 14px */;
    line-height: 1.25rem/* 20px */;
  }
  .profile_doc br {
    {% comment %} display: none; {% endcomment %}
  }
  .profile_doc input[type="file"]::-webkit-file-upload-button {
    padding-left: 0;
    padding-right: 0;
    margin-left: 0.5rem;
    border: 1px solid #e5e7eb;
    border-radius: 0.375rem;
    padding: 0.175rem 0.25rem;
    background-color: transparent;
    color: inherit;
    cursor: pointer;
  }
</style>

<div class="mx-auto max-w-7xl pt-0 lg:flex lg:gap-x-10 lg:px-8">

{% include "includes/settings_side_menu.html" %}

    {% comment %} 
    {% if user.profile.image %}
        <img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="{{user.profile.image.url}}" alt="user Avatar">
    {% else %}
        {% if user.profile.gender == '1' %}
            <img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="\static\images\boysAvatar.jpg" alt="user Avatar">
        {% else %}
            <img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="\static\images\girlsAvatar.jpg" alt="user Avatar">
        {% endif %}
    {% endif %}
    {% endcomment %}

{% comment %} LIST HEADING {% endcomment %}
  <main class="px-4 py-4 sm:px-6 lg:flex-auto lg:px-0 lg:py-10">
    <div class="mx-auto max-w-4xl space-y-16 sm:space-y-20 lg:mx-0 lg:max-w-none">
      <div class="space-y-12">



<div class="border-b border-gray-200 bg-white py-3">
  <div class=" flex flex-wrap items-center justify-between sm:flex-nowrap">
<div class="lg:flex lg:items-center lg:justify-between align-baseline" >

  <div class="min-w-0 flex-1">
    <h2 class="text-2xl font-bold leading-7 text-indigo-600 sm:truncate sm:text-3xl sm:tracking-tight">
        Your Suggestions
    </h2>
    <p class="mt-3 text-lg leading-8 text-gray-600">List of the suggestions you made, This is for your records as well as to view how many shadchanim have viewed your suggestion</a>
  </div>
</div>
    {% comment %}
    <div class="ml-4 mt-2 flex-shrink-0">
      <button type="button" class="relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Create</button>
    </div> 
    {% endcomment %}
</div>
</div>
{% comment %} START OF LIST {% endcomment %}
<ul role="list" class="divide-y divide-gray-100" x-data="{selected_modal: '', 'details_open': false,   'suggestion_id': '',
  'suggestion_by_first_name': '',
  'suggestion_by_last_name': '',
  'message': '',
  'email': '',
  'phone_number': '',
  'boys_first_name': '',
  'boys_last_name': '',
  'boys_mothers_name':'',
  'boys_fathers_name': '',
  'boys_age': '',
  'boys_country': '',
  'boys_city': '',
  'girls_first_name': '',
  'girls_last_name': '',
  'girls_mothers_name': '',
  'girls_fathers_name': '',
  'girls_age': '',
  'girls_country': '',
  'girls_city': '',
  'amount': '',}">
    {% for suggestion in suggestions  %}
        {% include "match_app/includes/suggestion_detail_modal.html"  with suggestion=suggestion%}
        <li class="relative w-full flex flex-col px-4 py-5 hover:bg-gray-50 sm:px-6 lg:px-8"   @click="
                          details_open=true, 
                          boys_first_name = '{{ suggestion.boys_first_name|default:"None"|escapejs }}', 
                          boys_last_name = '{{ suggestion.boys_last_name|default:"None"|escapejs }}', 
                          boys_mothers_name = '{{ suggestion.boys_mothers_name|default:"None"|escapejs }}', 
                          boys_fathers_name = '{{ suggestion.boys_fathers_name|default:"None"|escapejs }}',
                          boys_age = '{{ suggestion.boys_age|default:"None"|escapejs }}', 
                          boys_country = '{{ suggestion.boys_country|default:"None"|escapejs }}', 
                          boys_city = '{{ suggestion.boys_city|default:"None"|escapejs }}', 
                          girls_first_name = '{{ suggestion.girls_first_name|default:"None"|escapejs }}', 
                          girls_last_name = '{{ suggestion.girls_last_name|default:"None"|escapejs }}', 
                          girls_mothers_name = '{{ suggestion.girls_mothers_name|default:"None"|escapejs }}', 
                          girls_fathers_name = '{{ suggestion.girls_fathers_name|default:"None"|escapejs }}', 
                          girls_age = '{{ suggestion.girls_age|default:"None"|escapejs }}', 
                          girls_country = '{{ suggestion.girls_country|default:"None"|escapejs }}', 
                          girls_city = '{{ suggestion.girls_city|default:"None"|escapejs }}', 
                          amount = '{{ suggestion.amount|default:"None"|escapejs }}', 
                          ranking = '{{ suggestion.get_ranking_display|default:"None"|escapejs }}',
                          suggestion_by_first_name = '{{ suggestion.made_by.first_name|escapejs }}',
                          suggestion_by_last_name = '{{ suggestion.made_by.last_name|escapejs }}',
                          message = '{{ suggestion.message|default:"None"|escapejs }}',
                          email = '{{ suggestion.email|default:"None"|escapejs }}',
                          phone_number = '{{ suggestion.phone_number|default:"None"|escapejs }}'
                      ">
            {% comment %} BOYS INFO {% endcomment %}
            <div class="flex w-full justify-between gap-x-6">
                <div class="flex min-w-0 gap-x-4">
                    {% if suggestion.for_boy %}
                        {% if suggestion.for_boy.profile.image %}
                            <img class="mx-auto h-12 w-12 flex-shrink-0 rounded-full" src="{{suggestion.for_boy.profile.image.url}}" alt="">
                        {% else %}
                            <img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="\static\images\boysAvatar.jpg" alt="">
                        {% endif %}
                    {% else %}
                        <img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="\static\images\boysAvatar.jpg" alt="">
                    {% endif %}
                    <div class="min-w-0 flex-auto">
                        <p class="text-sm font-semibold leading-6 text-gray-900">
                            <a href="#">
                            <span class="absolute inset-x-0 -top-px bottom-0"></span>
                            {{suggestion.boys_first_name}} {{suggestion.boys_last_name}}
                            </a>
                        </p>
                        <p class="mt-1 flex text-xs leading-5 text-gray-500">
                            <a class="relative pointer-events-none"><span>Age:</span> {{suggestion.boys_age}}</a>
                        </p>
                    </div>
                </div>
                {% comment %} GIRLS INFO {% endcomment %}
                <div class="flex min-w-0 gap-x-4">
                    <div class="min-w-0 flex-auto">
                        <p class="text-sm font-semibold leading-6 text-gray-900 text-right">
                            <a href="#">
                                <span class="absolute inset-x-0 -top-px bottom-0"></span>
                                {{suggestion.girls_first_name}} {{suggestion.girls_last_name}}
                            </a>
                        </p>
                        <p class="mt-1 flex text-xs leading-5 text-gray-500">
                            <a class="relative "><span>Age:</span> {{suggestion.girls_age}}</a>
                        </p>
                    </div>
                    {% if suggestion.for_girl %}
                    {% if suggestion.for_girl.profile.image %}
                    <img class="mx-auto h-12 w-12 flex-shrink-0 rounded-full" src="{{suggestion.for_girl.profile.image.url}}" alt="">
                    {% else %}
                    <img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="\static\images\girlsAvatar.jpg" alt="">
                    {% endif %}
                    {% else %}
                    <img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="\static\images\girlsAvatar.jpg" alt="">
                    {% endif %}
                </div>
            </div>
                {% comment %} SUGGESTION META DATA {% endcomment %}
                
             <div class="mt-2 rounded-md flex flex-row shrink-0 items-center gap-x-4 w-full ">
                <div class="flex flex-row justify-between w-full py-1">
                    <button class="text-xs leading-6 text-gray-500 pl-2" title="Amount of Shadchanim that viewd this suggestion">
                     {{ suggestion.num_views }} view{{ suggestion.num_views|pluralize }}
                    </button>
                    <p class="mt-1 text-xs leading-5 text-gray-500 pr-2" title="How long ago this suggestion was created"> {{ suggestion.created|timesince }} ago</p>
                </div>
            </div>  
        </li>

    {% empty %}
        <h1>No Suggestions</h1>
    {% endfor %}
 
</ul>
{% include 'match_app/user_pagination.html' with page=suggestions %}
</main>
</div>
</div>
</div>
{% endblock content %}